# Generated by Django 2.0.4 on 2018-04-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180425_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_max_bet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_max_bet', to='core.Bet'),
        ),
    ]
