# Generated by Django 2.0.4 on 2018-04-26 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auction_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_max_bet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_max_bet', to='core.Bet'),
        ),
    ]
